language: python
sudo: required
services:
  - docker
python:
  - "2.7"
install: "pip install -r dev-requirements.pip"
script:
  - pylint lecli && py.test tests
  - cd docker && docker-compose run lecli
